//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnsOfAsked
    {
        public int kod_quest { get; set; }
        public int kod_asked { get; set; }
        public Nullable<int> kod_ans { get; set; }
        public string answer { get; set; }
    
        public virtual Asked Asked { get; set; }
        public virtual AnsOfQuest AnsOfQuest { get; set; }
        public virtual Questions Questions { get; set; }


        public override int GetHashCode()
        {
            return this.kod_asked;
        }
        public override bool Equals(object obj)
        {
            AnsOfAsked tmp = obj as AnsOfAsked;
            if (tmp == null) return false;
            return this.GetHashCode() == tmp.GetHashCode();
        }

    }
}
