//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skarim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skarim()
        {
            this.Questions = new HashSet<Questions>();
        }
    
        public int kod_skr { get; set; }
        public string name_skr { get; set; }
        public Nullable<int> kod_user { get; set; }
        public Nullable<System.DateTime> startdate_skr { get; set; }
        public Nullable<System.DateTime> lastdate_skr { get; set; }
        public string logo_skr { get; set; }
        public string jpg_skr { get; set; }
        public string bgcolor_skr { get; set; }
        public string fountcolor_skr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Questions> Questions { get; set; }
        public virtual Users Users { get; set; }
    }
}
